### ISSUE TITLE
Several issues with 2.3.2

### ISSUE THREAD

**Issue by Dxvid64** [fizi/BS_Gaming_01#2]
Hi, whilst preparing a new Machinima website over the past week, and using e107 2.3.2, I have noticed several things not working, most of the time, (and I suspect others I haven't noticed yet), so I have had to switch to my second choice Bootstrap 3 theme.  These include the "Login" and "PM" buttons not working, no "Comments" option showing up for News posts and the "New Topic" and "Options" buttons not working in the Forum.  The site can be found here,

http://mprem2.epizy.com

I was discussing these and other issues in another Github thread,

https://github.com/e107inc/e107/issues/4767

when "Jimmi08" kindly pointed me here.

If you need to see these issues live I could install a second, test, version of the site with BS Gaming installed (the main site is now live) and give you admin access to it.
Cheers,
David.

**Comment by Jimmi08** [comment]
@Dxvid64 Nobody will help you if you do issues this way, sorry. 
one problem, one issue, please

Example:
no "Comments" option showing up for News posts

What do you mean? It works for me
![image](https://user-images.githubusercontent.com/5429548/169042940-17088380-f444-424e-816a-691a2ec2978b.png)


Nobody has time to guess what you mean (no offense please).  With chrome, you can paste image directly here. 

I can see the New topic too
![image](https://user-images.githubusercontent.com/5429548/169043344-9bf8639d-b77f-481d-a8ea-dde4af059a7b.png)

Options too
![image](https://user-images.githubusercontent.com/5429548/169043471-d3dfd003-3174-4977-8bcf-074f226f7091.png)

PM too:

![image](https://user-images.githubusercontent.com/5429548/169043565-df291019-e483-4de8-bc62-c817f4ad7cb0.png)

So is it clear what I mean?  If you start to answer all your issues, it will be a mess soon. So one problem, one issue. Ok?

**Comment by Jimmi08** [comment]
No problem, everybody started...
Click on 
![image](https://user-images.githubusercontent.com/5429548/169046771-91d8ed00-3aff-43c3-a448-a54f24240699.png)
and describe what is problem with login button.

Your description  is needed because "login button not working" for theme developer  is this:
![image](https://user-images.githubusercontent.com/5429548/169047193-9633d0fe-bc3e-4b26-81b3-8a2d58353f4e.png)

And it works.

If the login process is not working (the user is not logged in), then it is a core stuff/issue and the theme developer will not help you.

**Comment by Jimmi08** [comment]
5 separate issues - it is easier that way.   And I can ask questions while you answer another one. Login button - you mean that one I posted screen, correct?

**Comment by Dxvid64** [comment]
yes top right.  I'm off to get some lunch but will make the five posts when I get back.
